#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'getinline'
require 'optparse'

options = {}

option_parser = OptionParser.new do |opts|
  executable_name = File.basename($PROGRAM_NAME)
  opts.banner = "
    getinline inlines CSS styles for HTML email development.

    Usage: #{executable_name} file_name
  "
end

begin
  option_parser.parse!
  rescue OptionParser::InvalidOption => error
  puts "Getinline doesn't recognize that #{ error }"
  exit
  rescue OptionParser::AmbiguousOption => error
  puts "That's an #{ error}"
  exit
end

file_contents = ARGF.read
transformer = Getinline::Transformer.new(file_contents)
puts transformer.transform
