#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'getinline'
require 'optparse'

options = {}

option_parser = OptionParser.new do |opts|
  executable_name = File.basename($PROGRAM_NAME)
  opts.banner = "
    getinline inlines CSS styles for HTML email development.

    Usage: #{executable_name} file_name
  "
end

begin
  option_parser.parse!
  rescue OptionParser::InvalidOption => error
  puts "Getinline doesn't recognize that #{ error }"
  exit
  rescue OptionParser::AmbiguousOption => error
  puts "That's an #{ error}"
  exit
end

if ARGV.empty?
  puts "    error: you must specify a file name"
  puts option_parser.help
else
  file_name = ARGV[0]
  file = File.open(file_name, "r")
  raw_text = file.read
  file.close
  transformer = Getinline::Transformer.new(raw_text)
  puts transformer.transform
end
